name: crisprware
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - biopython>=1.8
  - guidescan>=2.2
  - pybedtools>=0.9
  - matplotlib
  - pybigwig
  - pip
  - pip:
    - lightgbm==3.3.5
    - rs3>=0.0.15
